### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Romz24** [badasintended/megane#13]
On entering the game, I get a crash when using your mod and the crashlog is simply missing. The only thing I have is a line with errors from server logs. When I remove the megane mod the problem goes away.

**Megane:** **3.1.2**
**Minecraft:** **1.16.5**
**Fabric API:** 0.30.0
**Fabric Loader:** 0.11.1
**AppliedEnergistics2:** 8.1.0-alpha.13

```
[20:02:23] [main/FATAL]: Mixin prepare failed preparing appliedenergistics2.MTileWailaDataProvider in megane-impl.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:876) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:715) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:648) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:514) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:439) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:415) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:285) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-loader-0.11.1.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-loader-0.11.1.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_271]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_271]
	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45) ~[fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112) ~[fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99) ~[fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184) ~[fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:137) [fabric-loader-0.11.1.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27) [fabric-loader-0.11.1.jar:?]
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:825) ~[gson-2.8.0.jar:?]
	at mcp.mobius.waila.utils.JsonConfig.lambda$new$0(JsonConfig.java:31) ~[Hwyla-fabric-1.16.2-1.9.23-79.jar:?]
	at mcp.mobius.waila.utils.JsonConfig$CachedSupplier.get(JsonConfig.java:87) ~[Hwyla-fabric-1.16.2-1.9.23-79.jar:?]
	at mcp.mobius.waila.utils.JsonConfig.get(JsonConfig.java:56) ~[Hwyla-fabric-1.16.2-1.9.23-79.jar:?]
	at badasintended.megane.impl.mixin.MixinPlugin.shouldApplyMixin(MixinPlugin.java:38) ~[8b71373d-1c7f-4212-9bee-bbae003e5fdf.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.shouldApplyMixin(PluginHandle.java:132) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.shouldApplyMixin(MixinInfo.java:978) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:943) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:872) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	... 23 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385) ~[gson-2.8.0.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:825) ~[gson-2.8.0.jar:?]
	at mcp.mobius.waila.utils.JsonConfig.lambda$new$0(JsonConfig.java:31) ~[Hwyla-fabric-1.16.2-1.9.23-79.jar:?]
	at mcp.mobius.waila.utils.JsonConfig$CachedSupplier.get(JsonConfig.java:87) ~[Hwyla-fabric-1.16.2-1.9.23-79.jar:?]
	at mcp.mobius.waila.utils.JsonConfig.get(JsonConfig.java:56) ~[Hwyla-fabric-1.16.2-1.9.23-79.jar:?]
	at badasintended.megane.impl.mixin.MixinPlugin.shouldApplyMixin(MixinPlugin.java:38) ~[8b71373d-1c7f-4212-9bee-bbae003e5fdf.jar:?]
	at org.spongepowered.asm.mixin.transformer.PluginHandle.shouldApplyMixin(PluginHandle.java:132) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.shouldApplyMixin(MixinInfo.java:978) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:943) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:872) ~[sponge-mixin-0.8.2+build.24.jar:0.8.2+build.24+unknown-b24.git-unknown]
	... 23 more
```

**PS: It is worth noting that the error does not change at all if I remove the appliedenergistics2 mod**

**Comment by deirn** [comment]
can i see your `.minecraft/config/waila/megane-impl-mixin.json`?

**Comment by Romz24** [comment]
It is very strange why the content of the file is displayed as `NULNULNUL...`
Perhaps something happened and it broke? I have never touched or edited it manually.

[megane-impl-mixin.json.txt](https://github.com/badasintended/megane/files/5983311/megane-impl-mixin.json.txt)

**Comment by deirn** [comment]
i have no idea why it's like that...
try deleting the json

**Comment by Romz24** [comment]
I deleted this file, the problem is solved.
