### ISSUE TITLE
Compat Request

### ISSUE THREAD

**Issue by Laifsyn** [badasintended/megane#44]
[Mythic Metals Decorations](https://www.curseforge.com/minecraft/mc-mods/mythicmetals-decorations/files) has custom chests. Should I submit a ticket at their side instead?
`[17:36:31] [Server thread/ERROR]: Something went wrong when retrieving data for nourl.mythicmetalsdecorations.blocks.chest.MythicChestBlockEntity at (685, 71, 413)
[17:36:31] [Server thread/ERROR]: Stacktrace:
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1263.method_5439()" because "this.inventory" is null
	at lol.bai.megane.api.provider.base.InventoryItemProvider.getSlotCount(InventoryItemProvider.java:28) ~[megane-api-7.1.0-89cb0e829622943b.jar:?]
	at lol.bai.megane.runtime.data.block.BlockInventoryData.append(BlockInventoryData.java:37) ~[megane-runtime-7.2.0-6113e6bb7d6f830c.jar:?]
	at lol.bai.megane.runtime.data.block.BlockData.appendServerData(BlockData.java:54) ~[megane-runtime-7.2.0-6113e6bb7d6f830c.jar:?]
	at mcp.mobius.waila.network.PacketExecutor.requestBlockEntity(PacketExecutor.java:116) ~[wthit-fabric-4.8.1.jar:?]
	at mcp.mobius.waila.fabric.FabricPacketSender.lambda$initMain$10(FabricPacketSender.java:75) ~[wthit-fabric-4.8.1.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.redirect$bod000$redirectExecuteTask(class_1255.java:1021) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:16788) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:768) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$cdf000$modifiedRunLoop(MinecraftServer.java:5905) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by deirn** [comment]
Should already fixed in 7.5.1

**Comment by Laifsyn** [comment]
![image](https://user-images.githubusercontent.com/99366187/167310273-428031ce-c6e2-46ed-9d93-891359fe6e6b.png)
Compat confirmed. Thanks!
